apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment_name }}
  name:  {{ .Values.deployment_name }}
spec:
  replicas: {{ .Values.replica_number }}
  selector:
    matchLabels:
      app:  {{ .Values.deployment_name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app:  {{ .Values.deployment_name }}
    spec:
      containers:
      - image: buddhi82/flasklinuxcmd:v1
        name:  {{ .Values.deployment_name }}
        resources: {}
status: {}
